#!/bin/bash
dlfail() {
	echo Download failed. Check your internet connection or see http://users.v-lo.krakow.pl/~zlmch/mirror/
	exit 1
}

wget http://users.v-lo.krakow.pl/~zlmch/mirror/freeciv-android-dep.tgz -Ofreeciv-android-dep.tgz || dlfail
tar xvzf freeciv-android-dep.tgz
cp -r dep/* ./
rm -r dep


wget http://pygame.renpy.org/dl/old/pygame-package-0.9.3.tar.bz2 -Opygame-package.tar.bz2 || dlfail
tar xvjf pygame-package.tar.bz2
mkdir android/build 2> /dev/null
mv pygame-package-0.9.3/ android/build/pygame

cp zlib.mk zlib-1.2.5/Android.mk
rm -r android/build/pygame/src
ln -s $PWD/android/src android/build/pygame/src
