/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zielm_p4a_Wrapper */

#ifndef _Included_com_zielm_p4a_Wrapper
#define _Included_com_zielm_p4a_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zielm_p4a_Wrapper
 * Method:    _init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zielm_p4a_Wrapper_init0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
